export const projectsData = [
  {
    id: "proj1",
    category: "powerbi",
    featured: true,
    bars: [40, 70, 55, 90, 65, 80],
    title: "Retail Sales Forecasting Dashboard",
    desc: "Power BI dashboard analyzing 2 years of sales data to forecast next-quarter demand, reducing inventory cost by 15%.",
    tags: ["Power BI", "SQL", "DAX"],
    githubUrl: "#",
  },
  {
    id: "proj2",
    category: "sql",
    featured: true,
    bars: [60, 35, 75, 50, 85, 45],
    title: "E-commerce Customer Analysis (SQL)",
    desc: "Deep-dive SQL analysis of customer purchase behavior using joins, CTEs and window functions to segment high-value customers.",
    tags: ["SQL", "MySQL", "Window Functions"],
    githubUrl: "#",
  },
  {
    id: "proj3",
    category: "statistics",
    featured: false,
    bars: [50, 80, 65, 40, 70, 95],
    title: "Customer Churn Prediction Analysis",
    desc: "Statistical and EDA-driven analysis identifying key churn indicators, helping flag at-risk customers with 82% precision.",
    tags: ["Statistics", "EDA", "Python"],
    githubUrl: "#",
  },
  {
    id: "proj4",
    category: "excel",
    featured: false,
    bars: [45, 60, 90, 55, 70, 35],
    title: "HR Attrition Excel Dashboard",
    desc: "Interactive Excel dashboard with pivot tables and slicers surfacing attrition trends for HR decision-making.",
    tags: ["Excel", "Pivot Table", "Power Query"],
    githubUrl: "#",
  },
  {
    id: "proj5",
    category: "cleaning",
    featured: false,
    bars: [55, 40, 80, 60, 45, 75],
    title: "Messy Sales Data Cleaning Pipeline",
    desc: "Cleaned and standardized a 100K-row raw sales dataset — removed duplicates, fixed formats, and handled missing values.",
    tags: ["Data Cleaning", "Power Query", "Excel"],
    githubUrl: "#",
  },
  {
    id: "proj6",
    category: "powerbi",
    featured: false,
    bars: [65, 50, 85, 40, 75, 60],
    title: "Finance KPI Dashboard",
    desc: "Executive Power BI dashboard tracking revenue, margin and cash-flow KPIs across 5 business units.",
    tags: ["Power BI", "DAX", "Finance"],
    githubUrl: "#",
  },
];
